# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PLPullPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # 七牛云拉流
  pod 'PLPlayerKit', '~> 3.4.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'SDCycleScrollView', '~> 1.80'
  pod 'SDWebImage', '~> 5.3.1'


  # Pods for PLPullPlayer

  target 'PLPullPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PLPullPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
